version: "2.1"
services:

  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./heimdall:/config
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - duckdns-config/env.txt
    volumes:
     - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  my-journal:
    build:
      context: ./my-journal-config
      dockerfile: dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./sonarr:/config
    ports: 
      - 8989:8989
    restart: unless-stopped


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./radarr:/config
    ports:
      - 7878:7878
    restart: unless-stopped


  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - CUSTOM_PORT=8082
      - TZ=Europe/Paris
    volumes:
      - ./calibre:/config
    ports:
      - 8082:8082
      - 8181:8181
      - 8081:8081
    restart: unless-stopped
